mariadbのバックアップを実装した

diff --git a/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/argo-workflows-backup.yaml b/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/argo-workflows-backup.yaml
--- a/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/argo-workflows-backup.yaml
+++ b/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/argo-workflows-backup.yaml
@@ -26,16 +26,37 @@ spec:
   templates:
     - name: default
       steps:
+        - - name: generate-timestamp
+            template: get-timestamp
         - - name: patch-statefulset-to-0
             template: patch-statefulset-to-0
         - - name: wait-for-scale-to-0
             template: wait-for-scale-to-0
         - - name: run-backup
             template: run-backup
+          - name: run-mariadb-backup
+            template: run-mariadb-backup
+            arguments:
+              parameters:
+                - name: timestamp
+                  value: "{{steps.generate-timestamp.outputs.result}}"
+          - name: wait-complete-mariadb-backup
+            template: wait-complete-mariadb-backup
+            arguments:
+              parameters:
+                - name: timestamp
+                  value: "{{steps.generate-timestamp.outputs.result}}"
         - - name: patch-statefulset-to-1
             template: patch-statefulset-to-1
         - - name: wait-for-scale-to-1
             template: wait-for-scale-to-1
+
+    - name: get-timestamp
+      script:
+        image: alpine
+        command: [sh]
+        source: |
+          echo $(date +%Y%m%d-%H%M%S)
 
     - name: patch-statefulset-to-0
       script:
@@ -128,7 +149,58 @@ spec:
           - name: pbs-tmpfs
             mountPath: /root/.cache
       
-    # FIXME ここにMariaDBのメンテ完了を待つ処理を入れる必要がある
+    - name: run-mariadb-backup
+      inputs:
+        parameters:
+          - name: timestamp
+      resource:
+        action: create
+        manifest: |
+          apiVersion: k8s.mariadb.com/v1alpha1
+          kind: Backup
+          metadata:
+            name: mariadb-backup--{{inputs.parameters.timestamp}}
+          spec:
+            mariaDbRef:
+              name: mariadb
+            storage:
+              s3:
+                bucket: mariadb-backups
+                prefix: mcserver--debug-s1
+                endpoint: seichi-private-plugin-blackhole-minio.minio:9000
+                accessKeyIdSecretKeyRef:
+                  name: minio-access-secret
+                  key: MINIO_ACCESS_KEY
+                secretAccessKeySecretKeyRef:
+                  name: minio-access-secret
+                  key: MINIO_ACCESS_SECRET
+
+    - name: wait-complete-mariadb-backup
+      inputs:
+        parameters:
+          - name: timestamp
+      activeDeadlineSeconds: 300 # 5分待っても上がってこない場合は諦める
+      script:
+        image: bitnami/kubectl:1.32.1
+        command: ["/bin/sh", "-c"]
+        source: |
+          while true; do
+            TYPE_FAILED=$(kubectl get backup mariadb-backup--{{inputs.parameters.timestamp}} -n seichi-debug-minecraft -o jsonpath="{.status.conditions[?(@.type=='Failed')].status}")
+            TYPE_COMPLETE=$(kubectl get backup mariadb-backup--{{inputs.parameters.timestamp}} -n seichi-debug-minecraft -o jsonpath="{.status.conditions[?(@.type=='Complete')].status}")
+
+            if [ "$TYPE_FAILED" = "True" ]; then
+              echo "mariadb-backup failed!"
+              exit 1
+            fi
+
+            if [ "$TYPE_COMPLETE" = "True" ]; then
+              echo "mariadb-backup completed successfully!"
+              exit 0
+            fi
+
+            echo "Still waiting for mariadb-backup to complete..."
+            sleep 5
+          done
 
     - name: patch-statefulset-to-1
       script:
